/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_verisign_getdns_wrapper_GetDNS */

#ifndef _Included_com_verisign_getdns_wrapper_GetDNS
#define _Included_com_verisign_getdns_wrapper_GetDNS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_verisign_getdns_wrapper_GetDNS
 * Method:    createContext
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_verisign_getdns_wrapper_GetDNS_createContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_verisign_getdns_wrapper_GetDNS
 * Method:    general
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_verisign_getdns_wrapper_GetDNS_general
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_verisign_getdns_wrapper_GetDNS
 * Method:    destroyContext
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_verisign_getdns_wrapper_GetDNS_destroyContext
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
