/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_verisign_getdns_wrapper_GetDNS */

#ifndef _Included_com_verisign_getdns_wrapper_GetDNS
#define _Included_com_verisign_getdns_wrapper_GetDNS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_verisign_getdns_wrapper_GetDNS
 * Method:    createContext
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_verisign_getdns_wrapper_GetDNS_createContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_verisign_getdns_wrapper_GetDNS
 * Method:    generalSync
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Integer;Ljava/util/HashMap;Ljava/util/HashMap;)Lcom/verisign/getdns/wrapper/GetDNSReturn;
 */
JNIEXPORT jobject JNICALL Java_com_verisign_getdns_wrapper_GetDNS_generalSync
  (JNIEnv *, jobject, jobject, jstring, jint, jobject);

/*
 * Class:     com_verisign_getdns_wrapper_GetDNS
 * Method:    destroyContext
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_verisign_getdns_wrapper_GetDNS_destroyContext
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
