/* DO NOT EDIT THIS FILE - it is machine generated */
#include <arpa/inet.h>
#include "getdns/getdns.h"

/* Header for class com_verisign_getdns_GetDNSContext */

getdns_dict*
getdns_util_create_ip(const char* ip);

int
isPrintable(char* data, int size);
