/* DO NOT EDIT THIS FILE - it is machine generated */
#include <arpa/inet.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "getdns/getdns.h"

/* Header for class com_verisign_getdns_GetDNSContext */

getdns_dict*
getdns_util_create_ip(const char* ip);
